### ISSUE TITLE
Bin file?

### ISSUE THREAD

**Issue by mxrxtr** [ATOMNFT/M5stick-Marauder#1]
Could you add a bin file plaese?

**Comment by ATOMNFT** [comment]
Sure can. Give me a few and I'll post it.

**Comment by mxrxtr** [comment]
Thanks

**Comment by mxrxtr** [comment]
And where can i find it then? Thx

**Comment by ATOMNFT** [comment]
> And where can i find it then? Thx

https://github.com/ATOMNFT/M5stick-Marauder/tree/main/Bin%20Files

Sorry for the delay
