### ISSUE TITLE
Arduino IDE settings for Plus 2

### ISSUE THREAD

**Issue by kazz2020** [ATOMNFT/M5stick-Marauder#3]
Hi
What are correct arduino ide settings for compiling from source?

**Comment by ATOMNFT** [comment]
Go to select board and choose esp32/m5stick-c. Minimal spiffs with ota. You also need the correct user_setup files.

**Comment by ATOMNFT** [comment]
> Hi What are correct arduino ide settings for compiling from source?

Go to select board and choose esp32/m5stick-c. Minimal spiffs with ota. You also need the correct user_setup files.
