### ISSUE TITLE
BLE-Spam Crash

### ISSUE THREAD

**Issue by Antimorph** [ATOMNFT/M5stick-Marauder#7]
BLE-Spam runs for a second and then the M5StickC Plus2 crashes and reboots.

**Comment by ATOMNFT** [comment]
I will take a look at this issue and see if I can address it today as well. Thank you.

**Comment by ATOMNFT** [comment]
> BLE-Spam runs for a second and then the M5StickC Plus2 crashes and reboots.

Which version of marauder was giving that issue so I know where to look as it was addressed in the 13.10 And I thought I did the edits in the 1.0.0 ver as well.

**Comment by Antimorph** [comment]
> > BLE-Spam runs for a second and then the M5StickC Plus2 crashes and reboots.
> 
> Which version of marauder was giving that issue so I know where to look as it was addressed in the 13.10 And I thought I did the edits in the 1.0.0 ver as well.

I am so sorry! I just checked M5Burner again and I flashed it from the wrong repo.
I received the StickC Plus 2 yesterday and flashed marauder at 5:20 am today.
You were version works perfect!

**Comment by ATOMNFT** [comment]
> > > BLE-Spam runs for a second and then the M5StickC Plus2 crashes and reboots.
> > 
> > 
> > Which version of marauder was giving that issue so I know where to look as it was addressed in the 13.10 And I thought I did the edits in the 1.0.0 ver as well.
> 
> I am so sorry! I just checked M5Burner again and I flashed it from the wrong repo. I received the StickC Plus 2 yesterday and flashed marauder at 5:20 am today. You were version works perfect!

No worries and thanks for the reply.
