### ISSUE TITLE
[Bug] Can't get out Wifi Packet Monitor

### ISSUE THREAD

**Issue by Dtrieb** [ATOMNFT/M5stick-Marauder#9]
Can't get out Wifi Packet Monitor.
It shows me Mac Adresses and I can't return to the menu.

**Comment by Dtrieb** [comment]
Okay after a reboot it works with long press the "M5" Button

**Comment by ATOMNFT** [comment]
> Okay after a reboot it works with long press the "M5" Button

Thank you. I'll take a look at this today.
